# references:
# * https://www.objc.io/issues/6-build-tools/travis-ci/
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode9.4
language: swift
cache: cocoapods
podfile: Podfile
before_install:
 - gem install cocoapods # Since Travis is not always on latest version
 - pod install
script:
- set -o pipefail && xcodebuild test -enableCodeCoverage YES -workspace RxBiBinding.xcworkspace -scheme RxBiBinding -sdk iphonesimulator11.4 -destination 'platform=iOS Simulator,name=iPhone 6,OS=11.4' ONLY_ACTIVE_ARCH=NO | xcpretty
- pod lib lint
